// Copyright 2021 yuzu Emulator Project
// Licensed under GPLv2 or any later version
// Refer to the license.txt file included.

#version 430 core

layout (local_size_x = 4, local_size_y = 4) in;

layout(binding = 0, r16ui) readonly uniform uimage2D bgr_input;
layout(binding = 1, r16ui) writeonly uniform uimage2D bgr_output;

void main() {
    imageStore(bgr_output, ivec2(gl_GlobalInvocationID.xy), imageLoad(bgr_input, ivec2(gl_GlobalInvocationID.xy)));
}
